### ISSUE TITLE
Handle page linking with ID instead of slug

### ISSUE THREAD

**Issue by gravling** [Registercentrum/stratum-cms#101]
Currently all pages are linked by the slug e.g.  `För professionen` -> `foer-professionen' based on the title name. If someone would change the title or move the page to a different menu the direct link would be altered and result in broken links. It would probably be a good idea to link pages with ObjectIDs instead in order to keep links intact.

**Comment by kriar** [comment]
Discussed. Resolved to link based on id rather on slug. Obvious risk for text change and broken links.
