### ISSUE TITLE
Add support for processing of register specific styles in production

### ISSUE THREAD

**Issue by gravling** [Registercentrum/stratum-cms#130]
Up till now Keystone has been loaded all less files and processed them on the request, which is not viable for production. There is currently no solution to loading register specific styles if they are supposed to alter the global style variables. A simple css file would be easy to add.

**Comment by rogsa** [comment]
Can't we just have a task to compile less after we make changes? I mean, it will most often be during a initial phase of a register project that we need to alter the appearance. After that changes will be rare.

With a register specific css for overrides, it would be hard to mimic the effect of setting certain variables, for example `@font-size-base` . This variable will be reflected in most `font-size` in site.min.css (86 occurrences as of now). `@brand-primary` would probably be problematic too.
