### ISSUE TITLE
Better support for less than five items in jumbotron

### ISSUE THREAD

**Issue by rogsa** [Registercentrum/stratum-cms#135]
The items displayed in the jumbotron looks nice if there are five of them but not so good with fewer items. The implementation relies on a "fake" 5-column layout (`col-md-15`), that is not fluid. This could be solved by using a fixed table layout (see [jsFiddle](https://jsfiddle.net/medicor/xcapz0sm/)), that works regardless of the number of columns.

**Comment by gravling** [comment]
I agree that there needs to be support for e.g. 3,4,5 in a row, however one of the problems is that you don't want to show them all on one line in every resolution which is currently why it's divided by the same grid logic as the rest of the components.

**Comment by rogsa** [comment]
Yes, I realize this but it can be solved. There are some "flaws" today anyway, according too me. `xs-12` would probably look better since two columns on a 4 inch screen is one column too many. 

Nevertheless, when experimenting a bit I saw that if I just turned off `width: 20%` and `float: left` in `col-md-15` it works pretty well. Stretches nicely in "large device" mode, at least in Chrome.
