### ISSUE TITLE
Sub domains and SSL certificate

### ISSUE THREAD

**Issue by rogsa** [Registercentrum/stratum-cms#136]
Our SSL certificate doesn't seem to be valid when used with "four-level" sub domains, as in "shpr.cms.registercentrum.se"? If "*.registercentrum.se" in our SSL certificate means only three-level domains, we cannot use "<shortname>.cms.registercentrum.se" as our URL scheme. Ramin will check this with our certificate issuer.

**Comment by rogsa** [comment]
Unfortunately, it was confirmed from issuer that only a single-level sub domains can be used with our certificate, so a domain on the form "a.b.registercentrum.se" will not work, only "a.registercentrum.se". This means that we have some name clashes to address, for example "shpr.registercentrum.se" and "boa.registercentrum.se" are already in use, although they can probably be dropped some time after the Stratum CMS is in production. But during the intermediate phase we need a solution.

**Comment by gravling** [comment]
Guessing this could be closed now
