### ISSUE TITLE
Widget template

### ISSUE THREAD

**Issue by rogsa** [Registercentrum/stratum-cms#146]
Today there is some code that renders the source code for widget with an iframe. I assume this is only a placeholder. It needs to be replaced with a template that renders widget invokation through the widget loader: Syntax is:
```
<script src="/api/widgets/RC/Loader?widget=RC/NumberOfRegistrations&target=sw-container1"></script>
```
where `widget` is the widget name or the string "registrations", and `target` is the name of the container where the widget should be rendered.

I suggest that container elements are auto generated by the CMS with IDs `sw-container1`, `sw-container2` and so forth, depending on the number of widgets that are set up on a single page. An alternativ ID could be the "slug" version of the widget name, eg. `sw-rc-numberofregistrations`.

Since the widget loader is framework independent it could also be placed in the CMS. As it is now, the widget loader reloads itself each time a widget is loaded, since it is "bootstrapped" through a CMS generated script tag. This could be a possible future improvement.

**Comment by gravling** [comment]
Error: `initializeExtJS is not defined @ RC/Loader:162`

**Comment by rogsa** [comment]
Looks like you have tested something but i can't see that the "widget loader" code is generated on a page with a widget? When the loader code is generated i will begin to test real scenarios.

**Comment by rogsa** [comment]
In the "146-widget-loader-template" branch (should have looked there first :wink:). Can we have this in master directly? With the widget name instead of the hard-coded "RC/NumberOfRegistration" in page.hbs? Then I can move on with both testing the loader further and starting with widgets for SHPR.

**Comment by gravling** [comment]
I can set the test-server to checkout the following branch instead, if that is the main reason.

**Comment by rogsa** [comment]
Ok. Or we can pull this in to master directly. I guess the line 
```
<script type="text/javascript" src="/stratum/api/widgets/RC/Loader?widget=RC/NumberOfRegistrations&target=sw-{{slug}}"></script>
```
should be something like 
```
<script type="text/javascript" src="/stratum/api/widgets/RC/Loader?widget={{stratumWidget.widgetSlug}}&target=sw-{{slug}}"></script>
```
?
