### ISSUE TITLE
Problem when widgets grow dynamically

### ISSUE THREAD

**Issue by rogsa** [Registercentrum/stratum-cms#166]
If a widget, for example a grid, grows downwards it writes over the footer. It seems to be related to the footer being `position: absolute`. If i untick this it reverts back to static which seems to work well, at least when it comes to this problem. Not a major problem but it look ugly for example in [this page](https://nyashpr.registercentrum.se/statistik) and [this one](https://nyashpr.registercentrum.se/projekt). It seems to be also be solvable by setting `margin-bottom` to `120px` or something in `.stratum-widget`.

**Comment by rogsa** [comment]
I fixed this by setting `margin-bottom` to `120px` on `.stratum-widget`in SHPRs theme. Setting `position` to `static` on `footer` invalidated the fixation of the footer to the bottom so that was not working. I'll guess we can address some of these issues later on but this works for me now. In the site specific LESS I have marked this as temporary fixes.

**Comment by gravling** [comment]
This is actually only related to Stratum/ExtJS css, which breaks parts of the layout, footer being one of them. I can create a new issue regarding this instead

**Comment by gravling** [comment]
Looks like the problems with `font-size` and `background-color` on body has been fixed since a last looked so then it would probably only be the margin on body which affects the layout. I skip creating another issue for this then :)

**Comment by rogsa** [comment]
Good. The Stratum theme (ie. the one in Stratum) contains a redefinition of the `.x-body` class in `ext-theme-stratum-all_extra.css`, which was the result of me extracting some of the theme's css that would otherwise interfere with KeystoneJS/Bootstrap when integrating applications and widgets. If we have further problems with `.x-body` we can (probably) address them there.

**Comment by rogsa** [comment]
Found the problem. In the release version of the Stratum theme (`ext-theme-stratum-all_01.css`) there was another `.x-body` definition that wasn't removed during the first fix in October. So there were discrepancies between the debug and release versions of the theme. All good now (as far as i know).
