### ISSUE TITLE
Adjust Stratum Widgets for CMS

### ISSUE THREAD

**Issue by RegisterRonny** [Registercentrum/stratum-cms#176]
- [x] Check that some Stratum (RC) Widgets can be converted
- [x] ÖNH / FONO Widgets
- [x] ÖNH / HNSV Widgets
- [x] ÖNH / ROR Widgets
- [x] ÖNH / HNSB Widgets
- [x] ~~ÖNH / TON Widgets (will be replaced by a separate project)~~
- [x] Change all widget's url's to /stratum/api/widgets...
- [x] Adjust all widgets to use the new //# identifier instead of //@

Make sure that SOME Stratum's widgets work both in Stratum and when included in Keystone Stratum CMS.

URL's need to begin with '/stratum'. Any references to page div's need to be replaced by the container provided by the page template in Stratum CMS.

**Comment by RegisterRonny** [comment]
Did some tests on selected Widgets and it seams to work.

Convert widgets for ÖNH (but not TON because they will undergo a bigger overhaul soon) at first.

**Comment by gravling** [comment]
You could setup a simple todo in the issue to indicate how far you've come in the progress
- [ ] Widgets in HNSV
- [ ] Widgets in Septum

for example, then there would be a progress ratio computed in github as well :smiley:

**Comment by RegisterRonny** [comment]
How to do this? :)

**Comment by gravling** [comment]
I added two to the main description, just copy paste and repeat ;)

**Comment by RegisterRonny** [comment]
Only testet a few Stratum Widgets for RC.
- RC/NumberOfRegistrations was already fixed
- PROM seams to work but there was no "bjudning" to look at, need more tests.

These seamed to work but needs more tests, restored them to the original state
- RC/ProjectDatabase requires initializing of object _pdbConf 
- Testade RC/RegistrationOverviewAll, seams to work but need more tests and specific parameters set

**Comment by gravling** [comment]
:thumbsup:
I think Roger has "ProjektDatabasen" up and running in keystone (nyashpr) already

**Comment by RegisterRonny** [comment]
Regarding HNSV widgets:
- Some called RC/RegistrationOverviewAll, didn't convert or test these
- HSNV/Sign and HNSV/Rehab work
- HNSV/PIRS, HNSV/CIRatio, HNSV/Rehab and HNSV/Audiology all need new R-Scripts instead of old calls to ReportServer.GetReport

**Comment by RegisterRonny** [comment]
Regarding ROR widgets:
Use RC/RatioComparisonWidget and configuration in Advanced settings instead of the widgets in ROR. See configuration last in each ROR widget!
