### ISSUE TITLE
Hide title of widget

### ISSUE THREAD

**Issue by rogsa** [Registercentrum/stratum-cms#184]
It should be possible to hide the title of a Stratum widget. Since widgets can be small, placed in multiple locations on a page, the title is not always meaningful. The titles are used in listing so the best way is perhaps an option "[x] hide title when displayed" in widget configuration.?

**Comment by rogsa** [comment]
Have temporarily used a "Zero Width Space" character (&#x200b;) to not show any content in the heading but the screen estate is still wasted.

**Comment by gravling** [comment]
Is this mainly a problem when placing a widget in "full width" mode?

**Comment by rogsa** [comment]
As of right now, yes. It is a problem in the full width page type, since the title of the page is mandatory (acceptable) AND the title of the widget is mandatory. So if I have a page with only a widget (no text), I would be forced to have two consecutive titles on the page. One of them needs to be non-mandatory. The problem is probably the same for non-full page widgets.

**Comment by gravling** [comment]
Introduced a new layout for widgets on pages. Set widget size to large and it will be displayed as part of the page content and without title.

**Comment by rogsa** [comment]
:+1:  Just a small request - could we switch order between content and widget? The content is now below the widget and my introductory text first comes below the widget. I think it would generally be more useful to have the content above and widget below.
