### ISSUE TITLE
Create dedicated static Registration Page

### ISSUE THREAD

**Issue by gravling** [Registercentrum/stratum-cms#26]
There should be a (as for now) static page for keeping the registration widget in one default page. 
- Should be part of the primary navigation
- Should import the RC/Registration widget from stratum in a script tag
- Should contain a container for with predefined id

**Comment by frelun** [comment]
Ask @rogsa for id

**Comment by rogsa** [comment]
As of now, "sw-rcregistrations" is used as id in loader.
