### ISSUE TITLE
Prepare backend for nodejs 4, ES6 and Keystone 0.4

### ISSUE THREAD

**Issue by gravling** [Registercentrum/stratum-cms#27]
Since the newer versions of nodejs e.g. have reported better performance regarding memory consumption and fully supports ES6 it might be a good idea to upgrade.

**Comment by gravling** [comment]
Currently it is not possible to upgrade to node 4.0.0 since keystone 0.3 is dependent on mongodb 3 which will not build under node 4.0.0. However I have been testing with the 0.4.0 alpha build of keystone which is utilizing mongodb 4 where this build problem is solved. 

Should we start using keystone 0.4.0 even though it is still unstable to be able to move on to node 4?

**Comment by rogsa** [comment]
I think it's better to wait for a stable release of KeystoneJS 0.4 and then use Node.js ^4.2.0, which is LTS (4.0 isn't). Otherwise we will risk going into production with an alpha/beta build. Are there other dependencies, outside of KeystoneJS that might cause trouble with Node.js 4.2.4?

**Comment by gravling** [comment]
4.2.6 should be the current long term version

**Comment by rogsa** [comment]
Hence the caret ;-)
