### ISSUE TITLE
Force page refresh after automatic logout

### ISSUE THREAD

**Issue by rogsa** [Registercentrum/stratum-cms#343]
To prevent this scenario:
![image](https://cloud.githubusercontent.com/assets/10866283/24202436/465ed8ea-0f13-11e7-95ff-4cbff4a9211f.png)

**Comment by gravling** [comment]
Should force refresh once "Stäng" is pressed

**Comment by gravling** [comment]
Also, issues are handled in pivotal tracker from now on :)

https://www.pivotaltracker.com/n/projects/1946395

**Comment by rogsa** [comment]
Forgot that issues has been moved to PT. Will continue there.
