### ISSUE TITLE
Remove quote, code and image from markdown toolbar

### ISSUE THREAD

**Issue by gravling** [Registercentrum/stratum-cms#52]
This affects: 
* `NewsItem`
* `BasePage`
* `RegisterInformation`

**Comment by RegisterRonny** [comment]
Couldn't find any Markdown objects in the Stratum-CMS code. Do you want to remove both single and double quotes? What do you mean by "code"? HTML tags? (Will also remove IMG tags).

**Comment by gravling** [comment]
Markdown is a simple syntax for content markup e.g. headlines, bullet lists etc. You can use it in these comments for example. 

If you look in the admin view for a `NewsItem` you should be able to se a markdown field if you select `News Type` to `Extended` then `Content Extended` consists of a textarea supporting Markdown

With quotes i meant an actual quote i.e. 
> A quote

Code I meant snippets of code
```
var example = 'hej';
```

**Comment by gravling** [comment]
The models `BasePage` and `NewsItem` should contain fields with type Markdown

**Comment by RegisterRonny** [comment]
RegisterInformation also uses Types.Markdown, want a change there too? Do you want these changes only locally in RegisterInformation, NewsItem and BasePage, or should it (through prototype?) be changed for all Markdown types if possible?

**Comment by gravling** [comment]
Might as well change it for `RegisterInformation` as well.

Not sure if I follow, could you paste a snippet or something?

**Comment by RegisterRonny** [comment]
The easy solution is to write something like:
'{ type: Types.Markdown, toolbarOptions: { hiddenButtons: 'Code' } }'
... but with more hidden buttons.

Just thought that it might be possible to set this option as a default for this Type, by overriding the object prototype or something.

**Comment by gravling** [comment]
Do the easy solution :wink:
