### ISSUE TITLE
Add proxy to stratum within cms

### ISSUE THREAD

**Issue by gravling** [Registercentrum/stratum-cms#60]
There should be a proxy within express which pipes all requests made to `/stratum/*` to stratum.registercentrum.se in order to eliminate cross domain requests

**Comment by gravling** [comment]
How should http/https be handled, should keystone always request over https to stratum or should this be dependent on how the client calls the proxy?

@Registercentrum/developers

**Comment by rogsa** [comment]
Since we most probably will run everything under https in the (near) future, this will not be an issue but in the mean time I suggest we use the same scheme (ie. //). Otherwise we open up for the possibility to deliver secured resources through a non-secure channel.

**Comment by rogsa** [comment]
I have tried some calls locally and it looks fine. I suggest that this branch is merged with develop and deployed to cms for further "production-like" testing. In that way it will be easier to start adapting Stratum and the widget loader.

**Comment by gravling** [comment]
Sounds like a plan I will just fix the dynamic selection of `http` or `https` first and then I will merge it with `develop`-branch
:shipit:
