### ISSUE TITLE
Add a model for Startpage

### ISSUE THREAD

**Issue by frelun** [Registercentrum/stratum-cms#8]
Use the sketches to develop a first take on how a start page should be presented with widgets
A widget should be represented by the model developed in #6
A startpage should consist of 
- Textbox with a short description of the register
- A set of widgets (presumably 5) with a corresponding description
- A presentation area for news roll/important message/etc.. (vague description, needs more spec)

**Comment by frelun** [comment]
The description of the register could possibly be housed in another model?

**Comment by brygu** [comment]
yes

**Comment by frelun** [comment]
Currently no concept of static pages as e.g.  "Start"-page in Keystone. Possible workaround would be to auto create a start page and set the list as `nocreate` and `nodelete` to keep it down to one instance. However this is something which is said to be addressed in 0.3.x milestone.
