### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by frelun** [Registercentrum/stratum-cms#9]
There should be a contact page which is realized by a selection of User instances from the admin UI.
A contact should presumably contain:
- Full name
- Picture (or placeholder)
- Email
- Phone?

**Comment by rogsa** [comment]
Work title or Category would probably be useful too, like "Registerkoordinator", "Registerhållare", "Statistiker", "Systemutvecklare" and so forth.

**Comment by frelun** [comment]
:+1:
