### ISSUE TITLE
Change develop branch to master

### ISSUE THREAD

**Issue by gravling** [Registercentrum/stratum-cms#93]
Try following the more flexible layout of [Github Flow](https://guides.github.com/introduction/flow/)  instead of the more complex [Git Flow](http://nvie.com/posts/a-successful-git-branching-model/)

In short; 
* merge current `develop` branch with `master`
* remove `develop` branch
* make `master` default branch in github

**Comment by rogsa** [comment]
Sounds good to me.

**Comment by brygu** [comment]
Perfect, even if it does not affect me so much (yet)
